### ISSUE TITLE
OC.Plugins missing

### ISSUE THREAD

**Issue by joschaschmiedt** [nextcloud/nextcloud-typings#126]
The Typescript compiler is complaining that 
```
Property 'Plugins' does not exist on type 'Nextcloud.v21.OC | Nextcloud.v22.OC | Nextcloud.v23.OC'.
  Property 'Plugins' does not exist on type 'OC'.ts(2339)
```
Am I missing something here?

**Comment by susnux** [comment]
> We'd have to check where OC.Plugins is defined

Previously in [`core/js/js.js`](https://github.com/nextcloud/server/commit/c02ef695217f42dff501e481a50f4669d1cb1f29#diff-57b3577317bba610551412b0e6ef357ccde94c2b31ea1a20505be44303821061) but now in [`/core/src/OC/plugins.js`](https://github.com/nextcloud/server/blob/master/core/src/OC/plugins.js)

>what versions have it and then add it here to the typings.

It was introduced with NC8 so I think it can go into common:
https://github.com/nextcloud/server/commit/c02ef695217f42dff501e481a50f4669d1cb1f29
